### Register a new user
POST http://localhost:8000/api/register/
Content-Type: application/json

{
  "username": "test",
  "email": "test@example.com",
  "password": "josh1231"
}

### Login with the registered user
POST http://localhost:8000/api/token/
Content-Type: application/json

{
  "username": "test",
  "password": "josh1231"
}