# Generated by Django 5.2.1 on 2025-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('status', models.CharField(choices=[('playlist', 'Playlist'), ('completed', 'Completed'), ('inprogress', 'In Progress')], max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
