# Generated by Django 5.2.1 on 2025-06-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamelog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='game',
            field=models.IntegerField(),
        ),
    ]
