# Generated by Django 5.2.1 on 2025-06-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gamelog_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelog',
            old_name='game',
            new_name='game_id',
        ),
    ]
