# Generated by Django 5.2.1 on 2025-06-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_reviewcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='reviewCount',
            new_name='review_count',
        ),
    ]
